name = "cicd"
version = "0.1.0"

[dependencies]
cicd = "=0.9.0-pre.2"
distrib = "=0.9.0-pre.2"
fs = "=0.9.0-pre.2"
http = "=0.9.0-pre.2"
log = "=0.9.0-pre.2"
net = "=0.9.0-pre.2"
process = "=0.9.0-pre.2"
std = "=0.9.0-pre.2"
work = "=0.9.0-pre.2"

[entrypoints]
advanced = "cicd/advanced::main"
main = "cicd::main"
